### ISSUE TITLE
Update asset URL

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/foodandfarming#10]
Minor change: Josie set up a new report prior to migration that she's since had to replicate on the new site. One of the report links broke due to it no longer being September and the new asset is in a different folder. 
Please change it so that https://foodandfarming.ca/custom/uploads/2020/10/Carrot-Value-Chain-Analysis-Report-2020.pdf is updated to https://foodandfarming.ca/custom/uploads/2020/09/Carrot-Value-Chain-Analysis-Report-2020.pdf (i.e. just swap out the 10 in the date for 09)

**Comment by lionelmann** [comment]
Done
