### ISSUE TITLE
Increase file upload size

### ISSUE THREAD

**Issue by rstender** [hypenotic/foodandfarming#11]
Client is unable to upload larger files to server. See note below:

> "This is much smaller than it used to be - I wasn't sure if this was discussed with Janet or what, but we have a new Action Plan to upload now, which is a larger file. Is this a quick fix, can it be changed so I can upload larger files? "

**Comment by rstender** [comment]
Here's the file she's trying to upload. It's only 16.5MB!

[GHFFA Action Plan - Oct 2020.pdf](https://github.com/hypenotic/foodandfarming/files/5497360/GHFFA.Action.Plan.-.Oct.2020.pdf)

**Comment by lionelmann** [comment]
Max file uploads size allowed is increased from 2MB to 20MB. Closing

**Comment by rstender** [comment]
Thx Lionel!
