### ISSUE TITLE
Report Custom post type is AWOL. 

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/foodandfarming#7]
Hi Lionel!
In the shuffle, it looks like the  'Report' custom post type has vanished ('post_type' => 'report'). It is necessary to be able to add new content to the Research page (http://www.foodandfarming.ca/research/).
I am not sure what we do to bring it back, but their team is looking to add more reports to this list.
The Research template is here: https://github.com/hypenotic/foodandfarming/blob/staging/custom/themes/GTAAAC/page-research.php and the loop in question starts at line 28 (to give you an idea of the required fields)

I don't know if adding Meta Box will be sufficient to call this back, or if we need to rebuild it. 
Are the old 'reports' gone for good?
Please keep me posted.
Cat.

**Comment by lionelmann** [comment]
This needs to be rebuilt using metabox. It was using an old helper that is now depreciated and which was causing issues.
